[build]
  command = "npm install && npm run build"
  publish = "authorization_code/public"  
  functions ="functions"
  environment = { NODE_VERSION = "16" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  